version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db_immovable
    restart: always
    environment:
      POSTGRES_DB: immovable_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_immovable
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: [ "/app/wait-for-db.sh" ]

volumes:
  pgdata:
