# Generated by Django 4.1.3 on 2022-11-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annoucement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publishing_plataform", models.CharField(max_length=50)),
                (
                    "plataform_rate",
                    models.FloatField(
                        help_text="digite a taxa da plataforma. ex: 13.00"
                    ),
                ),
                ("date_time_create", models.DateTimeField(auto_now_add=True)),
                ("date_time_update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Immoble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("immoble_code", models.PositiveIntegerField(auto_created=True)),
                ("title", models.CharField(max_length=255)),
                ("guest_limit", models.IntegerField(max_length=6)),
                ("number_of_bathorroms", models.IntegerField(max_length=3)),
                ("accepted_pet", models.BooleanField(default=False)),
                ("cleaning_price", models.IntegerField(max_length=3)),
                ("date_activation", models.DateTimeField(auto_now_add=True)),
                ("date_time_create", models.DateTimeField(auto_now_add=True)),
                ("date_time_update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reserve_code", models.PositiveIntegerField(auto_created=True)),
                (
                    "total_price",
                    models.FloatField(
                        help_text="digite o valor da reserva total da reserva(ex: 952.38)"
                    ),
                ),
                ("comment_field", models.CharField(max_length=255)),
                ("number_of_guests", models.IntegerField(max_length=6)),
                ("check_in_date", models.DateField(auto_now_add=True)),
                ("check_out_date", models.DateField(auto_now=True)),
                ("date_time_create", models.DateTimeField(auto_now_add=True)),
                ("date_time_update", models.DateTimeField(auto_now=True)),
                (
                    "annoucement_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="immovablehutting.annoucement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="annoucement",
            name="immoble_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="immovablehutting.immoble",
            ),
        ),
    ]
