# Generated by Django 4.1.3 on 2022-11-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("immovablehutting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="immoble",
            name="guest_limit",
            field=models.IntegerField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="immoble",
            name="immoble_code",
            field=models.PositiveIntegerField(auto_created=True, unique=True),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="annoucement_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="id_annoucement",
                to="immovablehutting.annoucement",
            ),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="number_of_guests",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="limit_guests",
                to="immovablehutting.immoble",
            ),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="reserve_code",
            field=models.PositiveIntegerField(auto_created=True, unique=True),
        ),
    ]
