# Generated by Django 4.1.3 on 2022-11-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "immovablehutting",
            "0002_alter_immoble_guest_limit_alter_immoble_immoble_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="immoble",
            name="immoble_code",
            field=models.PositiveIntegerField(
                auto_created=True, blank=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="number_of_guests",
            field=models.IntegerField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                ],
                max_length=1,
            ),
        ),
    ]
