# Generated by Django 4.1.3 on 2022-11-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immovablehutting", "0004_alter_immoble_immoble_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="immoble",
            name="date_time_create",
            field=models.DateTimeField(default="null"),
        ),
    ]
