# Generated by Django 4.1.3 on 2022-11-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immovablehutting", "0005_alter_immoble_date_time_create"),
    ]

    operations = [
        migrations.AlterField(
            model_name="immoble",
            name="date_time_create",
            field=models.DateTimeField(default="2006-02-15 05:03:42"),
        ),
    ]
