# Generated by Django 4.1.3 on 2022-11-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("immovablehutting", "0007_remove_immoble_immoble_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="immoble",
            old_name="date_activation",
            new_name="activation",
        ),
    ]
