# Generated by Django 4.1.3 on 2022-11-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immovablehutting", "0008_rename_date_activation_immoble_activation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="immoble",
            name="activation",
            field=models.DateField(auto_now_add=True),
        ),
    ]
