# Generated by Django 4.1.3 on 2022-11-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("immovablehutting", "0009_alter_immoble_activation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="immoble",
            old_name="date_time_create",
            new_name="create",
        ),
        migrations.RenameField(
            model_name="immoble",
            old_name="date_time_update",
            new_name="update",
        ),
    ]
