# Generated by Django 4.1.3 on 2022-11-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immovablehutting", "0010_rename_date_time_create_immoble_create_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="immoble",
            name="immoble_code",
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
