# Generated by Django 4.1.3 on 2022-11-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("immovablehutting", "0011_immoble_immoble_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annoucement",
            old_name="date_time_create",
            new_name="create",
        ),
        migrations.RenameField(
            model_name="annoucement",
            old_name="date_time_update",
            new_name="update",
        ),
        migrations.RenameField(
            model_name="reserve",
            old_name="date_time_create",
            new_name="create",
        ),
        migrations.RenameField(
            model_name="reserve",
            old_name="date_time_update",
            new_name="update",
        ),
    ]
