# Generated by Django 4.1.3 on 2022-11-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "immovablehutting",
            "0012_rename_date_time_create_annoucement_create_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="immoble",
            name="guest_limit",
            field=models.IntegerField(
                blank=True,
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
