# Generated by Django 4.1.3 on 2022-11-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immovablehutting", "0014_alter_immoble_number_of_bathorroms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="immoble",
            name="cleaning_price",
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
