# Generated by Django 4.1.3 on 2022-11-29 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("immovablehutting", "0016_alter_annoucement_plataform_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annoucement",
            name="immoble_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="immovablehutting.immoble",
            ),
        ),
    ]
