# Generated by Django 4.1.3 on 2022-11-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immovablehutting", "0017_alter_annoucement_immoble_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserve",
            name="total_price",
            field=models.FloatField(
                blank=True,
                help_text="digite o valor da reserva total da reserva(ex: 952.38)",
                null=True,
            ),
        ),
    ]
